[default]
timeout = 120

[style]
title = "에스콰이어 코리아 ─ 스타일"
url = "https://www.esquirekorea.co.kr/style"
entrySelector = "div.contents_wrap div.contents div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = "div.contents"

[watch]
title = "에스콰이어 코리아 ─ 와치"
url = "https://www.esquirekorea.co.kr/watch"
entrySelector = "div.contents_wrap div.contents div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = "div.contents"

[carandtech]
title = "에스콰이어 코리아 ─ 카&테크"
url = "https://www.esquirekorea.co.kr/carandtech"
entrySelector = "div.contents_wrap div.contents div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = "div.contents"

[food]
title = "에스콰이어 코리아 ─ 푸드"
url = "https://www.esquirekorea.co.kr/food"
entrySelector = "div.contents_wrap div.contents div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = "div.contents"

[life]
title = "에스콰이어 코리아 ─ 라이프"
url = "https://www.esquirekorea.co.kr/life"
entrySelector = "div.contents_wrap div.contents div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"

[people]
title = "에스콰이어 코리아 ─ 피플"
url = "https://www.esquirekorea.co.kr/people"
entrySelector = "div.contents_wrap div.contents div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = "div.contents"

[now]
title = "에스콰이어 코리아 ─ 나우"
url = "https://www.esquirekorea.co.kr/now"
entrySelector = "div.contents_wrap div.contents div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = "div.contents"

[eshop]
title = "에스콰이어 코리아 ─ 이샵"
url = "https://www.esquirekorea.co.kr/eshop"
entrySelector = "div.contents_wrap div.contents div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = "div.contents"
